(cl:in-package communication_test-msg)
(cl:export '(ENCORDER_LINEARMODULE-VAL
          ENCORDER_LINEARMODULE
          HALL_PUTTER_1_LEFT-VAL
          HALL_PUTTER_1_LEFT
          HALL_PUTTER_1_RIGHT-VAL
          HALL_PUTTER_1_RIGHT
          HALL_PUTTER_2_LEFT-VAL
          HALL_PUTTER_2_LEFT
          HALL_PUTTER_2_RIGHT-VAL
          HALL_PUTTER_2_RIGHT
          HALL_PUTTER_3_LEFT-VAL
          HALL_PUTTER_3_LEFT
          HALL_PUTTER_3_RIGHT-VAL
          HALL_PUTTER_3_RIGHT
))